name: Deploy Images to GHCR

on:
  push:
    branches: [ "dev" ]

jobs:
  unit-tests: 
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: '.'    
    steps:    
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pip and pytest
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt
    - name: Test with pytest
      run: |
        python3 -m pytest --import-mode=append tests/

  build-dev:
    # if: github.ref == 'refs/heads/dev'
    needs: unit-tests
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: '.'
    steps: 
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build, Tag, and push the Docker image"
        env:
          IMAGE_NAME: ghcr.io/manimatter/decluttarr
          IMAGE_TAG: dev
        run: |
          docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
