name: Deploy Images to GHCR

# env:
#   DOTNET_VERSION: '6.0.x' 

on:
  push:
    branches: [ "main" ]
    tags: ["v[0-9]+.[0-9]+.[0-9]*"]

jobs:
  unit-tests: 
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: './src/utils/'    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pip and pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov 
    - name: Test with pytest
      run: |
        pytest /home/runner/work/decluttarr/src/utils/test_nest_functions.py -vv   

  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: '.'
    steps: 
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: setversion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: "Build, Tag, and push the Docker image"
        env:
          IMAGE_NAME: ghcr.io/manimatter/decluttarr
          IMAGE_TAG: ${{ steps.setversion.outputs.new_tag }}
        run: |
          docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: "Build, Tag, and push the Docker image"
        env:
          IMAGE_NAME: ghcr.io/manimatter/decluttarr
          IMAGE_TAG: latest
        run: |
          docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG 