name: Deploy Images to GHCR

# env:
#   DOTNET_VERSION: '6.0.x' 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-decluttarr-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Checkout  
            uses: actions/checkout@v2  
            with:  
                fetch-depth: 0  

          - name: tag-version
            uses: juliansangillo/tag-version@v1.5
            with:  
                production-branch: main 

          - name: 'Build Inventory Image'
            run: |
              docker build -f docker/Dockerfile . --tag ghcr.io/manimatter/decluttarr:latest             
              docker push ghcr.io/manimatter/decluttarr:latest